### ISSUE TITLE
How to add checksum to the final css file name

### ISSUE THREAD

**Issue by rezaalavi** [kentaroi/eleventy-sass#10]
How can we have the final CSS file as [md5].css and how to retrieve this dynamically generated in name in the template?

**Comment by kentaroi** [comment]
What is the purpose of the checksum?

You can use `permalink` property to change CSS paths in `output` directory.
https://github.com/kentaroi/eleventy-sass#how-to-change-output-directory-for-css-files-compiled-from-sassscss

**Comment by rezaalavi** [comment]
It is to have a unique file with a very long cache expiration date of up to a year. Similar to what we have for the "Image".

How to get the generated filename in the template?

**Comment by kentaroi** [comment]
If you are talking about the cache buster, I recommend you to read the following article:
https://rob.cogit8.org/posts/2020-10-28-simple-11ty-cache-busting/

If you are not talking about the cache buster and you'd like to add checksum to CSS filenames, could you please tell me your situation, why you need a very long cache expiration date, etc. in detail. I will think about the easiest way to do that.

**Comment by rezaalavi** [comment]
Thanks, but that is not what I am looking for. There is no point in having a new timestamp for CSS when the CSS content rarely  changes.

Using hash for assets filename is a very well established practice.
You can just check the HTML code of github and you will see all CSS assets have their content hash. (e.g https://github.githubassets.com/assets/primer-10084108b209.css](view-source:https://github.githubassets.com/assets/primer-10084108b209.css)
You might also want to read this.
https://survivejs.com/webpack/optimizing/adding-hashes-to-filenames/

**Comment by kentaroi** [comment]
Now, I got it.
I will add this feature to the plugin.

**Comment by rezaalavi** [comment]
Thank you.

**Comment by kentaroi** [comment]
I just published v2.0.0, which includes the feature.

Since this is a major release, please update the plugin like this:
```bash
npm install eleventy-sass@2
```

Here is the usage:
https://github.com/kentaroi/eleventy-sass#rev-property
