### ISSUE TITLE
postcss with autoprefixer seems to not working

### ISSUE THREAD

**Issue by danielosbombelos** [kentaroi/eleventy-sass#14]
Hello. I'm having troubles to compiler prefixes with postcss + autoprefixer. Can you help out?

package.json:
`{
  "name": "zawada-stronka",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "serve": "npx @11ty/eleventy --serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@11ty/eleventy": "^1.0.2",
    "autoprefixer": "^10.4.8",
    "cssnano": "^5.1.13",
    "eleventy-sass": "^2.1.2",
    "postcss": "^8.4.16"
  },
  "browserslist": [
    "defaults"
  ]
}
`

.eleventy.js config:
`const eleventySass = require('eleventy-sass');
const postcss = require('postcss');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');

module.exports = function(eleventyConfig) {
    eleventyConfig.addPlugin(eleventySass, {
        sass: {
            style: 'compressed',
            sourceMap: false,
        },
        postcss: postcss([autoprefixer, cssnano]),
    });

    return {
        dir: {
            input: 'src',
            includes: '_includes',
            output: '_dist',
        },
        templateFormats: ['njk', 'html'],
        markdownTemplateEngine: 'njk',
        htmlTemplateEngine: 'njk',
        dataTemplateEngine: 'njk',
    }

}`

input: style.scss:
`body {
  background: yellow;
  background: yellow;

  transition: all .5s;
}`
output: style.css:
body{background:#ff0;transition:all .5s}

**Comment by kentaroi** [comment]
How about changing your "browserslist" in `package.json` as follows:
```json5
{
  // ...
  "browserslist": [
    "last 4 version"
  ]
  // ...
}
```

**Comment by danielosbombelos** [comment]
oh that did it! Thank you so much for the help! :)

**Comment by kentaroi** [comment]
You're welcome!
