### ISSUE TITLE
Collections-related oddity

### ISSUE THREAD

**Issue by brycewray** [kentaroi/eleventy-sass#15]
I am using `eleventy-sass` and `eleventy-plugin-rev` in the repo https://github.com/brycewray/eleventy_site. I have found an oddity, in that the Sass files accessed by `eleventy-sass` are showing up in Eleventy’s `collections.all` object. You can see this by cloning the repo, running it, and then checking the output in the following files within the created site, each of which accesses `collections.all` to create a list of the site’s content:

- `sitemap.xml` (regular sitemap file)
- `index.xml` (RSS feed file)
- `index.json` (JSON feed file)

I have tried this with and without the use of `eleventy-plugin-rev`, so I don’t believe that to be related.

**Note**: This is with Eleventy 2.0.0-canary.15, in case that matters.

In lieu of an actual fix, perhaps you could suggest a code workaround in the meantime?

Other than this, have been very impressed by these plugins, about which [I wrote yesterday](https://www.brycewray.com/posts/2022/09/cache-busting-eleventy-simpler-way-sass/). Thanks!

**Comment by kentaroi** [comment]
Thanks for filing the issue!
I just fixed it and published v2.1.3.
Hope this works.

Thank you very much for writing a wonderful blog post!!!!!
I'm really thrilled with it. Thank you very much :smile:

**Comment by brycewray** [comment]
> Thanks for filing the issue! I just fixed it and published v2.1.3. Hope this works.
> 
> Thank you very much for writing a wonderful blog post!!!!! I'm really thrilled with it. Thank you very much 😄

You’re very welcome! In the meantime, I was helped on the Eleventy Discord with an interim fix — just creating a new collection that is **only** Markdown files (https://discord.com/channels/741017160297611315/1021827942172590120/1021836670301130762) — so, if that doesn’t do the job, at least this will work.

**Comment by brycewray** [comment]
> Thanks for filing the issue! I just fixed it and published v2.1.3. Hope this works.

@kentaroi Just installed 2.1.3 and it does indeed. Thanks again!

**Comment by kentaroi** [comment]
Glad to hear that.
Thank YOU, @brycewray !
