### ISSUE TITLE
Possible typo in eleventy-plugin-rev usage example?

### ISSUE THREAD

**Issue by televators** [kentaroi/eleventy-sass#19]
Loving this plugin so far!

Was having a small issue with getting the `{{ 'scss/styles.scss' | inputToRevvedOutput }}` example to work. In the example, it shows the relative path as I typed it, but it doesn't work unless I add relative path from project root instead of the eleventy source directory ('src' in my case). Once I changed it to `{{ 'src/scss/styles.scss' | inputToRevvedOutput }}` it works fine.

Is that correct functionality or should it know to pull 'scss/styles.scs' from whatever source directory as defined in .eleventy.js config?

Thanks!

**Comment by kentaroi** [comment]
Thanks, @televators.

Although the doc may be confusing, it (passing a relative path from the project root) is the spec, actually.
However, I should admit that the spec (and the implementation) of `inputToRevvedOutput` is half-cooked and/or ugly.

**Comment by kentaroi** [comment]
I added `revvedOutput` filter in eleventy-sass@2.2.0 (eleventy-plugin-rev@1.1.0). Hope you like it.

For details:
https://github.com/kentaroi/eleventy-sass#rev-property
