### ISSUE TITLE
Question: Does this work with @import?

### ISSUE THREAD

**Issue by seangwright** [kentaroi/eleventy-sass#2]
I'm trying to use this plugin with Bootstrap 5, which hasn't migrated to `@use` and `@forward`.

Whenever I save a partial that is brought into my `main.scss` with `@include`, the eleventy build starts again, but the generated `.css` file is left unmodified. It's as if the cache isn't touched for the generated file.

**Comment by kentaroi** [comment]
I didn't write this plugin with `@import` in mind, but it should work.
Could you try the following command:
```bash
DEBUG=*EleventySass* npx @11ty/eleventy --serve
```
and you will get the dependency map of your SCSS files in your shell output.

Or, could you please show me a minimum code which doesn't work.

**Comment by kentaroi** [comment]
I confirmed that this plugin works with `@import` in my local environment.
Take a look at the following, if you like:
https://github.com/kentaroi/eleventy-sass-bootstrap-sample

If you found any bugs in the plugin, please attach the code that fails and your environment info.
