### ISSUE TITLE
Choose a custom input path

### ISSUE THREAD

**Issue by xplosionmind** [kentaroi/eleventy-sass#24]
I would like to put my styles folder (containing the main `.scss` file and its modules) in the root of my directory rather than within the input directory. Is there a way I can do so?

Thanks ❤️

**Comment by kentaroi** [comment]
eleventy-sass makes use of Eleventy's file watching functionality.
Therefore, your Sass/SCSS files should be inside your project's input directory.

For your use case, I recommend using the following plugin:
https://github.com/AramZS/eleventy-plugin-dart-sass

**Comment by xplosionmind** [comment]
Thanks, but this plugin is wonderful and I do not mind having to keep the `styles` directory inside the `input` directory to use it!

**Comment by kentaroi** [comment]
Thanks, @xplosionmind!
