### ISSUE TITLE
Custom output path (to src/_includes)

### ISSUE THREAD

**Issue by erlandh** [kentaroi/eleventy-sass#25]
Really appreciating your plugin and its straightforward documentation. Thanks!

I understand you can rewrite the output path using a permalink function, and I've done that using your example to write compiled CSS files to /css from an input /scss folder. 

However, what I'd like to do is implement inlining of critical CSS and defer loading non-critical styles using the [bundle plugin](https://github.com/11ty/eleventy-plugin-bundle). Seems like the way to do this is to write the compiled CSS output to eg. `src/_includes/css` rather than `dist/css` and then use the bundle plugin to inline eg. critical.css and make its own CSS file in dist from eg. defer.css and load that asynchronously.

I studied [compileOptions.permalink](https://www.11ty.dev/docs/languages/custom/#compileoptions.permalink-to-override-permalink-compilation) in the official 11ty docs but I couldn't see/understand if a slightly more complex permalink function could be used to write the output of eleventy-sass to somewhere inside the `src` folder.

Sorry if this is really obvious, I'm pretty new to 11ty and just not really sure if/how a `.replace()` can be used on the `filePathStem` variable to point back to somewhere in the src folder.

**Comment by kentaroi** [comment]
Thank you, @erlandh!

I don't know the bundle plugin, but how about writing `.eleventy.js`, for example, as follows:
```javascript
const sass = require('eleventy-sass');

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(sass, {
    compileOptions: {
      permalink: function(contents, inputPath) {
        return (data) => {
          return data.page.filePathStem.replace(/^\/scss\//, "../src/_includes/css/") + ".css";
        };
      }
    }
  });
  return {
    dir: {
      input: "src",
      output: "dist"
    }
  };
};
```

**Comment by erlandh** [comment]
Thanks! I didn't realise I could just point to the output folder, I thought it was doing some kind of replace _on_ the path, rather than replacing it wholesale 🤦  Anyway, thanks for bearing with me!

**Comment by kentaroi** [comment]
Not at all, @erlandh.
If you feel that your problem has been solved, please close the issue.

**Comment by kentaroi** [comment]
Sorry, I misread your comment, @erlandh.
It does replace each of the Sass/SCSS paths.
If you do not understand how to use permalink functions, please ask in https://github.com/11ty/eleventy/discussions or in the Eleventy's discord channel, instead of here.
