### ISSUE TITLE
Partials don't trigger recompile on latest version

### ISSUE THREAD

**Issue by ItsEthanH** [kentaroi/eleventy-sass#26]
So I have my project set up with the commonly known 7-1 architecture, using @forward and @use with a single main stylesheet, styles.scss.

Making a change to pages/_home.scss, and saving, doesn't cause a recompile. However, re-running npm start does cause a compile.

I've reverted the plugin to 1.3.1 and I can have my partials work like normal, so not too sure what's wrong with the latest version. Happy to share my code if needed :)

**Comment by kentaroi** [comment]
Thanks for filing the issue.
Can I have the versions of Eleventy and Node and the name and version of your OS?
If possible, can I have your log messages in DEBUG mode? For Example:
```bash
DEBUG=*EleventySass* npx @11ty/eleventy
```
and make a change to `pages/_home.scss`.

**Comment by ItsEthanH** [comment]
Hi Kentaro! Thanks for getting back to me so quickly :)

Certainly! I've got it all below for you:
**Node Version:** v20.3.1
**OS:** Windows. Full version/build info below.
![image](https://github.com/kentaroi/eleventy-sass/assets/89361954/c1ed8c5d-6cbf-4108-b445-146c15e30e8f)

**Debug Messaging:** I've attached the full log after making a change to this reply as a .txt file. I hope that's okay, I didn't want to miss anything out for you.

[log.txt](https://github.com/kentaroi/eleventy-sass/files/11850713/log.txt)

I can see that there's a message for not compiling _home, due to it starting with an underscore, but the 
@use and @forward have been set up.

For good measure, I've also done a quick replication video - just in case there's something obvious I may be missing!
https://youtu.be/MIkf2n17IPc

It's saying it'll take another half hour for the HD version to be processed for some reason 🤷🏻 

Let me know if there's anything else I can hand over to ya!

**Comment by ItsEthanH** [comment]
Almost forgot! From package.json:
"@11ty/eleventy": "^2.0.1",

**Comment by kentaroi** [comment]
Thank you for providing additional information, @ItsEthanH.

In order to isolate the problem, I just published eleventy-sass@2.2.2 with additional debugging outputs.

I'm sorry to trouble you, but can you please give me log messages in DEBUG mode with the same condition but with eleventy-sass@2.2.2?

**Comment by ItsEthanH** [comment]
Not a problem! I've included it in another text file below :)

This is for eleventy-sass@2.2.3:
[better-logging.txt](https://github.com/kentaroi/eleventy-sass/files/11857242/better-logging.txt)

**Comment by kentaroi** [comment]
Thank you so much!!!
From the Log, it seems that Eleventy is not calling eleventy-sass to compile styles.scss.
In fact, eleventy-sass uses the dependency management system introduced in Eleventy 2, instead of the dependency map inside eleventy-sass, if Eleventy is version 2 or later.

So I can't think of a way to fundamentally solve this problem, but to work around it, try the following:

1. Add delay like this (https://www.11ty.dev/docs/watch-serve/#add-delay-before-re-running):
```javascript
// .eleventy.js
module.exports = function(eleventyConfig) {
  eleventyConfig.setWatchThrottleWaitTime(100); // in milliseconds
};
```

2. If the above fix doesn't work, the only solution may be to turn off the cache:
```javascript
// .eleventy.js
const sass = require('eleventy-sass');
module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(sass, {
    compileOptions: {
      cache: false
    }
  });
};
```

**Comment by ItsEthanH** [comment]
Hello!

Turning off the cache seemed to fix the problem, which I think I'm totally fine with. Would I be correct in saying the only implication would be longer build times? If so, I can live with that. 

Thank you for your expert support up until now. Happy to not have to downgrade so many versions :)

**Comment by kentaroi** [comment]
You're welcome :)
Thank you too for the useful information you have provided.
Turning off the cache will have a negative impact on build times, but there should be no other issues.

**Comment by MHLut** [comment]
Hi! FYI. I found this issue but cannot reproduce it with version 2.2.3 (current version). You can probably close this ticket.

**Comment by ItsEthanH** [comment]
Hey! I think you're right :) Turned the caching option back on and it works as it should!

Thanks for the heads up - will close this one down for us all

@kentaroi just a heads up this is all working

**Comment by kentaroi** [comment]
Thanks a lot, @MHLut , @ItsEthanH !
