### ISSUE TITLE
linking to my css file in my layout file

### ISSUE THREAD

**Issue by derron1** [kentaroi/eleventy-sass#28]
Hi not sure how to link to the CSS file in my layout.. linking to the scss file doesn't work, or converts

**Comment by kentaroi** [comment]
Just add a link tag.
```html
<head>
  <link rel="stylesheet" href="/path/to/your/style.css" />
</head>
```

**Comment by kentaroi** [comment]
I close the issue because `rev` and `revvedOutput` filter functions do not seem to have any problems.
If you find a specific problem, please reopen the issue with information such as debug logs.
