### ISSUE TITLE
Changes to scss watch is not working

### ISSUE THREAD

**Issue by jeminpro** [kentaroi/eleventy-sass#3]
Very easy to use a plugin for compiling SCSS to CSS. One issue I found is that it complies with CSS files fine but later when I modify the SCSS file the CSS file is not reflecting the changes until I run the command `npm run start` again. BTW in npm start, I have the following command `npx @11ty/eleventy --serve`. Please let me know how to resolve this issue?

**Comment by kentaroi** [comment]
Thanks for reporting.
I'm sorry, but, in my local environment, there is no such issue.
Could you please show me a minimal Eleventy project that doen't recompile SCSS files when modified?

**Comment by jeminpro** [comment]
Thanks for your quick response. I have uploaded my project in git repo [here](https://github.com/jeminpro/Jeminpro)

**Comment by kentaroi** [comment]
Thank you, too.
I just confirmed it works fine in my environment:
node v17.8.0
macOS 12.3 Monterey

**Comment by jeminpro** [comment]
I am trying it on LTS node version 16.14.2 on windows 11.

Just to confirm have you run the command `npm run start` and changed SCSS file which intern reflected the changes in CSS file?

**Comment by kentaroi** [comment]
Yes. I run `npm run start`, open `localhost:8080` in my browser, and changed `background-color` in `scss/site.scss` file.
Browser automatically updated the background color.

Could you try the following command:
```bash
DEBUG=*EleventySass* npm run start
```
and modify your `scss/site.scss` file, for example, and paste the DEBUG output here, please?
It will be a big help for me to figuring it out.

**Comment by kentaroi** [comment]
Thanks for giving me your environment info.
I just tested it again on LTS node version 16.14.2 on macOS, and it works.

**Comment by kentaroi** [comment]
When you run `npx @11ty/eleventy --serve` or `npm run start` prepended with `DEBUG=*EleventySass* `,
if the plugin detects a file change, you will see something like the following output:
```
[11ty] File changed: src/scss/site.scss
  Dev:EleventySass eleventy.beforeWatch queue: [ './src/scss/site.scss' ] +6s
  Dev:EleventySass getCacheKey(contents, ./src/scss/_reset.scss) -> ./src/scss/_reset.scss2022-03-27T15:50:15.077Zinitial +29ms
  Dev:EleventySass getCacheKey(contents, ./src/scss/site.scss) -> ./src/scss/site.scss2022-03-27T15:50:20.805Z +4ms
  Dev:EleventySass Has compiled ./src/scss/site.scss +44ms
  Dev:EleventySass:DependencyMap Dependencies for ./src/scss/site.scss is not changed: [./src/scss/_reset.scss] +6s
  EleventySass:SourceMapStore public/css/site.css.map written.. +6s
[11ty] Wrote 19 files in 0.10 seconds (5.3ms each, v1.0.0)
[Browsersync] Reloading Browsers...
```

**Comment by jeminpro** [comment]
When I try the above command I get the following error 

DEBUG=*EleventySass*: The term 'DEBUG=*EleventySass*' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by kentaroi** [comment]
I'm sorry I wrote the script for *nix.

I'm not familiar with the Windows environment, but
if you are using cmd.exe, try the following:
```
set DEBUG=*EleventySass* & npm run start
```
if you are using PowerShell:
```
$env:DEBUG="*EleventySass*"; npm run start
```

**Comment by kentaroi** [comment]
I'm not sure, but this might be related to https://github.com/11ty/eleventy/issues/2183.

**Comment by jeminpro** [comment]
Below is what I get doesn't look like plugging is getting the watch event :(

[Browsersync] Serving files from: public
[11ty] File changed: src\scss\site.scss
[11ty] Writing public/sitemap.xml from ./src/sitemap.xml.njk
[11ty] Writing public/feed/feed.xml from ./src/feed/feed.njk
[11ty] Writing public/feed/.htaccess from ./src/feed/htaccess.njk
[11ty] Writing public/feed/feed.json from ./src/feed/json.njk
[11ty] Writing public/css/site.css from ./src/scss/site.scss
[11ty] Writing public/posts/fourthpost/index.html from ./src/posts/fourthpost.md (njk)
[11ty] Writing public/posts/secondpost/index.html from ./src/posts/secondpost.md (njk)
[11ty] Writing public/posts/thirdpost/index.html from ./src/posts/thirdpost.md (njk)
[11ty] Writing public/posts/2018/firstpost/index.html from ./src/posts/2018/firstpost.md (njk)
[11ty] Writing public/404.html from ./src/404.md (njk)
[11ty] Writing public/posts/index.html from ./src/archive.njk
[11ty] Writing public/index.html from ./src/index.njk
[11ty] Writing public/page-list/index.html from ./src/page-list.njk
[11ty] Writing public/tags/index.html from ./src/tags-list.njk
[11ty] Writing public/tags/second-tag/index.html from ./src/tags.njk
[11ty] Writing public/tags/number-2/index.html from ./src/tags.njk
[11ty] Writing public/tags/posts-with-two-tags/index.html from ./src/tags.njk
[11ty] Writing public/tags/another-tag/index.html from ./src/tags.njk
[11ty] Writing public/about/index.html from ./src/about/index.md (njk)
[11ty] Benchmark      9ms   9%   215× (Configuration) "url" Nunjucks Filter
[11ty] Wrote 19 files in 0.10 seconds (5.3ms each, v1.0.0)
[11ty] Watching…
[Browsersync] Reloading Browsers...

**Comment by jeminpro** [comment]
Tried again below is the debug logs

[Browsersync] Serving files from: public
[11ty] File changed: src\scss\site.scss
  Dev:EleventySass eleventy.beforeWatch queue: [ './src\\scss\\site.scss' ] +34s
  Dev:EleventySass getCacheKey(contents, ./src/scss/_reset.scss) -> ./src/scss/_reset.scss2022-03-27T16:36:15.062Zinitial +77ms
  Dev:EleventySass getCacheKey(contents, ./src/scss/site.scss) -> ./src/scss/site.scss2022-03-27T16:36:15.064Zinitial +8ms
[11ty] Wrote 19 files in 0.11 seconds (5.8ms each, v1.0.0)
[Browsersync] Reloading Browsers...

**Comment by kentaroi** [comment]
Thanks a lot.
I'll investigate it.

**Comment by kentaroi** [comment]
I just published v1.1.5.
Hope this works.

**Comment by kentaroi** [comment]
I just published v1.1.5.
Hope this works.

**Comment by jeminpro** [comment]
Excellent, I have tested it now and it works, thanks a lot. Please close this issue.

I have one query unrelated to this. In the build script for production, how do we implement cache buster i.e. adding some hash version to the end of the css URL, is there any built-in functionality in this plugin?

**Comment by kentaroi** [comment]
Thanks for testing!
Your contributions made this plugin work on Windows. Thank you very much.

I'm sorry the plugin does not have any cache buster functionality.
Thanks for reminding me. I'll think about it

**Comment by kentaroi** [comment]
I thought about cache buster, and if I understand correctly, cache buster is how you refer to (CSS) files.
Therefore, it is not so related to this plugin, because `eleventy-sass` doesn't refer to CSS files, but generates CSS files.

As you may know, all you have to do when implementing cache buster is just add a query parameter at the end of the value for `href` attribute in the stylesheet `link` tags.
There seems to be lots of articles on how to implement cache buster in Eleventy projects.
For example:
https://rob.cogit8.org/posts/2020-10-28-simple-11ty-cache-busting/

**Comment by jeminpro** [comment]
> I thought about cache buster, and if I understand correctly, cache buster is how you refer to (CSS) files. Therefore, it is not so related to this plugin, because `eleventy-sass` doesn't refer to CSS files, but generates CSS files.
> 
> As you may know, all you have to do when implementing cache buster is just add a query parameter at the end of the value for `href` attribute in the stylesheet `link` tags. There seems to be lots of articles on how to implement cache buster in Eleventy projects. For example: https://rob.cogit8.org/posts/2020-10-28-simple-11ty-cache-busting/


Perfect exactly what I needed, thanks

**Comment by kentaroi** [comment]
You're welcome:smile:
