### ISSUE TITLE
PurgeCSS integration

### ISSUE THREAD

**Issue by jalberto** [kentaroi/eleventy-sass#31]
To make PurgeCSS work, I need to do this:
```
const postcssPurgecss = require("@fullhuman/postcss-purgecss")({content: ['./_site/**/*.html'], css: ["./_site/**/*.css"]});

  eleventyConfig.addPlugin(eleventySass,{
   ...
    postcss: postcss([
      postcssPurgecss
    ])
  });
...
```

is it possible to get automatically the content from the pipeline?

Thanks!

**Comment by kentaroi** [comment]
Thank you for your question, @jalberto!
However, I'm not sure how to get automatically the content.

Have you asked this question in Eleventy's Discord channel or GitHub discussion?
It seems to be a question about Eleventy's API or how Eleventy works.

**Comment by jalberto** [comment]
Thanks, @kentaroi, you are right, I may ask first there.

I asked here because I am using `eleventy-sass` for all the PostCSS pipeline.

Will `eleventy-sass` works well if I extract all PostCSS pipeline to its own plugin?

**Comment by kentaroi** [comment]
It seems that I may not fully understand your question. What eleventy-sass does is simply call the `process` method on the PostCSS object given by the user, and use its return value for css.
https://github.com/kentaroi/eleventy-sass/blob/77ce75081e0d584e97bf4e41e88e9ad06cd2e2af/lib/compile.js#L33-L40

**Comment by kentaroi** [comment]
Since there seems to be no comments, I'll add a few more.

I am not a PurgeCSS user so I am not sure, but I don't think using PurgeCSS directly with eleventy-sass is a good idea, since there is no guarantee that the HTMLs have been generated at the time of compilation of Sass/SCSS.

You might want to check out [eleventy-plugin-vite](https://github.com/11ty/eleventy-plugin-vite/).

**Comment by kentaroi** [comment]
Thank you for your question. While I appreciate your interest in my library, this issue appears to be outside the scope of what I can support. I recommend exploring alternative solutions or addressing this issue with another library that may be better suited to address your specific needs. I'm closing this issue for now, but feel free to reopen it if you have any further questions on this issue.
