### ISSUE TITLE
Sass with PostCSS

### ISSUE THREAD

**Issue by netopolit** [kentaroi/eleventy-sass#8]
Is there a (easy) way to apply PostCSS transformations to resulting compiled CSS file?
Other ideas for combining this plugin with PostCSS are welcome.

Thanks and sorry for too many questions :)

**Comment by kentaroi** [comment]
https://www.11ty.dev/docs/config/#transforms should be the easiest way.

**Comment by kentaroi** [comment]
@netopolit 
I've just published version 1.3.0.
You can use PostCSS with eleventy-sass a bit easier from this version.
https://github.com/kentaroi/eleventy-sass#postcss-key
https://github.com/kentaroi/eleventy-sass#how-to-use-postcss-and-autoprefixer-to-support-older-browsers

**Comment by netopolit** [comment]
@kentaroi Thank you!

**Comment by kentaroi** [comment]
@netopolit Not at all!
