### ISSUE TITLE
Does not compile .sass formatted files correctly

### ISSUE THREAD

**Issue by WinstonMarvel** [kentaroi/eleventy-sass#9]
When using SCSS formatting everything seems fine but not while using the indented SASS formatting. 

How to reproduce:
- .sass file with indented style should be present in the src directory
While using @import for the file it works. Eg. importing something from includes or something with an underscore. Eg. style.scss importing an  _foo.sass file works. However if the file style.scss was a style.sass file with the indented style formatting,  errors are thrown

**Comment by kentaroi** [comment]
Thanks a lot for filing the issue.
I've just fixed it and published v1.3.1.
Hope this works.
